# Generated by Django 2.2.2 on 2019-06-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(db_index=True, help_text='Telegram user ID.', verbose_name='User ID')),
                ('gid', models.BigIntegerField(db_index=True, help_text='Telegram group ID this user has sent message into.', verbose_name='Group ID')),
                ('has_messages', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the profile was created at.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the profile was updated at.', verbose_name='Updated at')),
                ('grace_at', models.DateTimeField(blank=True, help_text='Date and time the profile grace period started at.', null=True, verbose_name='Grace started at')),
                ('warnings', models.PositiveSmallIntegerField(default=0, help_text='Warnings this user have.', verbose_name='Warnings')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
                'unique_together': {('uid', 'gid')},
            },
        ),
    ]
